# Generated by Django 4.0 on 2021-12-14 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=1000)),
                ('categories', models.TextField(max_length=10)),
                ('city', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=1000)),
                ('headquarters', models.CharField(max_length=255)),
                ('internships', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.internship')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='applied_internships',
            field=models.ManyToManyField(to='main.Internship'),
        ),
    ]
