# Generated by Django 4.0 on 2021-12-14 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_internship_company_student_applied_internships'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='internships',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.internship'),
        ),
        migrations.RemoveField(
            model_name='student',
            name='applied_internships',
        ),
        migrations.AddField(
            model_name='student',
            name='applied_internships',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.internship'),
        ),
    ]
