# Generated by Django 4.0 on 2021-12-14 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_company_internships_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='description',
            field=models.TextField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='internship',
            name='categories',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='internship',
            name='description',
            field=models.TextField(max_length=10000),
        ),
    ]
