# Generated by Django 4.0 on 2021-12-14 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_company_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='internships',
        ),
        migrations.AddField(
            model_name='internship',
            name='company',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.company'),
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
