# Generated by Django 4.0 on 2021-12-14 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_company_internships_internship_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internship',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.company'),
        ),
    ]
