# Generated by Django 4.0 on 2021-12-15 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_customuser_options_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
