# Generated by Django 4.0 on 2021-12-15 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
