# Generated by Django 4.0 on 2021-12-15 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_delete_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internship',
            name='categories',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='internship',
            name='description',
            field=models.CharField(max_length=10000),
        ),
    ]
