# Generated by Django 4.0 on 2021-12-15 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_company_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('university', models.CharField(max_length=255)),
                ('internship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.internship')),
            ],
        ),
    ]
